yarnPath: .yarn/releases/yarn-2.4.2.cjs

packageExtensions:
  "@putout/compare@7":
    peerDependencies:
      try-catch: "*"
  "@putout/engine-parser@4":
    peerDependencies:
      try-catch: "*"
  "@putout/traverse@3":
    peerDependencies:
      try-catch: "*"
